@WZCNet_HostAddress = http://localhost:5187

GET {{WZCNet_HostAddress}}/api/employee/
Accept: application/json

###
GET {{WZCNet_HostAddress}}/api/employee/99
Accept: application/json
###
POST {{WZCNet_HostAddress}}/api/employee/
Accept: application/json
Content-Type: application/json

{
    "firstName":"Jan",
    "lastName":"Alleman            ",
    "dateOfBirth": "2009-01-05",
    "addresses":[{
        "streetName":"Begijnenstraat",
        "houseNumber":"1",
        "zipCode":"1234",
        "municipality":"Antwerpen"

    }]
}
###
POST {{WZCNet_HostAddress}}/api/employee/1/pin-generate
Accept: application/json
