@WZCNet_HostAddress = http://localhost:5187

GET {{WZCNet_HostAddress}}/api/employee/
Accept: application/json

###
GET {{WZCNet_HostAddress}}/api/employee/1
Accept: application/json
###
POST {{WZCNet_HostAddress}}/api/employee/
Accept: application/json
Content-Type: application/json

{
    "firstName":"      x         ",
    "lastName":"Alleman            ",
    "dateOfBirth": "2025-02-28",
    "addresses":[
        {
        "zipCode":"2000",
        "houseNumber":"1",
        "municipality":"      Antwerpen   ",
        "streetName":"    Begijnenstraat   ",
        "until":"2059-05-04"
    }
    ]
    
}
###